apiVersion: apps/v1
kind: Deployment
metadata:
  name: oplog-middleware
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oplog-middleware
  template:
    metadata:
      labels:
        app: oplog-middleware
    spec:
      containers:
        - name: oplog-middleware
          image: uhub.service.ucloud.cn/entropypool/oplog-middleware:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/OplogMiddleware
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: oplog-middleware-config
            items:
              - key: service-conf
                path: OplogMiddleware.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: oplog-middleware
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50780
      targetPort: 50780
    - name: grpc
      port: 50781
      targetPort: 50781
    - name: healthz
      port: 50782
      targetPort: 50782
    - name: prometheus
      port: 50783
      targetPort: 50783
  selector:
    app: oplog-middleware
