// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/NpoolPlatform/oplog-middleware/pkg/db/ent/oplog"
	"github.com/NpoolPlatform/oplog-middleware/pkg/db/ent/pubsubmessage"
	"github.com/NpoolPlatform/oplog-middleware/pkg/db/ent/schema"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oplogMixin := schema.OpLog{}.Mixin()
	oplog.Policy = privacy.NewPolicies(oplogMixin[0], schema.OpLog{})
	oplog.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := oplog.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	oplogMixinFields0 := oplogMixin[0].Fields()
	_ = oplogMixinFields0
	oplogMixinFields1 := oplogMixin[1].Fields()
	_ = oplogMixinFields1
	oplogFields := schema.OpLog{}.Fields()
	_ = oplogFields
	// oplogDescCreatedAt is the schema descriptor for created_at field.
	oplogDescCreatedAt := oplogMixinFields0[0].Descriptor()
	// oplog.DefaultCreatedAt holds the default value on creation for the created_at field.
	oplog.DefaultCreatedAt = oplogDescCreatedAt.Default.(func() uint32)
	// oplogDescUpdatedAt is the schema descriptor for updated_at field.
	oplogDescUpdatedAt := oplogMixinFields0[1].Descriptor()
	// oplog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oplog.DefaultUpdatedAt = oplogDescUpdatedAt.Default.(func() uint32)
	// oplog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oplog.UpdateDefaultUpdatedAt = oplogDescUpdatedAt.UpdateDefault.(func() uint32)
	// oplogDescDeletedAt is the schema descriptor for deleted_at field.
	oplogDescDeletedAt := oplogMixinFields0[2].Descriptor()
	// oplog.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	oplog.DefaultDeletedAt = oplogDescDeletedAt.Default.(func() uint32)
	// oplogDescEntID is the schema descriptor for ent_id field.
	oplogDescEntID := oplogMixinFields1[1].Descriptor()
	// oplog.DefaultEntID holds the default value on creation for the ent_id field.
	oplog.DefaultEntID = oplogDescEntID.Default.(func() uuid.UUID)
	// oplogDescAppID is the schema descriptor for app_id field.
	oplogDescAppID := oplogFields[0].Descriptor()
	// oplog.DefaultAppID holds the default value on creation for the app_id field.
	oplog.DefaultAppID = oplogDescAppID.Default.(func() uuid.UUID)
	// oplogDescUserID is the schema descriptor for user_id field.
	oplogDescUserID := oplogFields[1].Descriptor()
	// oplog.DefaultUserID holds the default value on creation for the user_id field.
	oplog.DefaultUserID = oplogDescUserID.Default.(func() uuid.UUID)
	// oplogDescPath is the schema descriptor for path field.
	oplogDescPath := oplogFields[2].Descriptor()
	// oplog.DefaultPath holds the default value on creation for the path field.
	oplog.DefaultPath = oplogDescPath.Default.(string)
	// oplogDescMethod is the schema descriptor for method field.
	oplogDescMethod := oplogFields[3].Descriptor()
	// oplog.DefaultMethod holds the default value on creation for the method field.
	oplog.DefaultMethod = oplogDescMethod.Default.(string)
	// oplogDescArguments is the schema descriptor for arguments field.
	oplogDescArguments := oplogFields[4].Descriptor()
	// oplog.DefaultArguments holds the default value on creation for the arguments field.
	oplog.DefaultArguments = oplogDescArguments.Default.(string)
	// oplogDescCurValue is the schema descriptor for cur_value field.
	oplogDescCurValue := oplogFields[5].Descriptor()
	// oplog.DefaultCurValue holds the default value on creation for the cur_value field.
	oplog.DefaultCurValue = oplogDescCurValue.Default.(string)
	// oplogDescHumanReadable is the schema descriptor for human_readable field.
	oplogDescHumanReadable := oplogFields[6].Descriptor()
	// oplog.DefaultHumanReadable holds the default value on creation for the human_readable field.
	oplog.DefaultHumanReadable = oplogDescHumanReadable.Default.(string)
	// oplogDescResult is the schema descriptor for result field.
	oplogDescResult := oplogFields[7].Descriptor()
	// oplog.DefaultResult holds the default value on creation for the result field.
	oplog.DefaultResult = oplogDescResult.Default.(string)
	// oplogDescFailReason is the schema descriptor for fail_reason field.
	oplogDescFailReason := oplogFields[8].Descriptor()
	// oplog.DefaultFailReason holds the default value on creation for the fail_reason field.
	oplog.DefaultFailReason = oplogDescFailReason.Default.(string)
	// oplogDescElapsedMillisecs is the schema descriptor for elapsed_millisecs field.
	oplogDescElapsedMillisecs := oplogFields[9].Descriptor()
	// oplog.DefaultElapsedMillisecs holds the default value on creation for the elapsed_millisecs field.
	oplog.DefaultElapsedMillisecs = oplogDescElapsedMillisecs.Default.(uint32)
	pubsubmessageMixin := schema.PubsubMessage{}.Mixin()
	pubsubmessage.Policy = privacy.NewPolicies(pubsubmessageMixin[0], schema.PubsubMessage{})
	pubsubmessage.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := pubsubmessage.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	pubsubmessageMixinFields0 := pubsubmessageMixin[0].Fields()
	_ = pubsubmessageMixinFields0
	pubsubmessageMixinFields1 := pubsubmessageMixin[1].Fields()
	_ = pubsubmessageMixinFields1
	pubsubmessageFields := schema.PubsubMessage{}.Fields()
	_ = pubsubmessageFields
	// pubsubmessageDescCreatedAt is the schema descriptor for created_at field.
	pubsubmessageDescCreatedAt := pubsubmessageMixinFields0[0].Descriptor()
	// pubsubmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	pubsubmessage.DefaultCreatedAt = pubsubmessageDescCreatedAt.Default.(func() uint32)
	// pubsubmessageDescUpdatedAt is the schema descriptor for updated_at field.
	pubsubmessageDescUpdatedAt := pubsubmessageMixinFields0[1].Descriptor()
	// pubsubmessage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pubsubmessage.DefaultUpdatedAt = pubsubmessageDescUpdatedAt.Default.(func() uint32)
	// pubsubmessage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pubsubmessage.UpdateDefaultUpdatedAt = pubsubmessageDescUpdatedAt.UpdateDefault.(func() uint32)
	// pubsubmessageDescDeletedAt is the schema descriptor for deleted_at field.
	pubsubmessageDescDeletedAt := pubsubmessageMixinFields0[2].Descriptor()
	// pubsubmessage.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	pubsubmessage.DefaultDeletedAt = pubsubmessageDescDeletedAt.Default.(func() uint32)
	// pubsubmessageDescEntID is the schema descriptor for ent_id field.
	pubsubmessageDescEntID := pubsubmessageMixinFields1[1].Descriptor()
	// pubsubmessage.DefaultEntID holds the default value on creation for the ent_id field.
	pubsubmessage.DefaultEntID = pubsubmessageDescEntID.Default.(func() uuid.UUID)
	// pubsubmessageDescMessageID is the schema descriptor for message_id field.
	pubsubmessageDescMessageID := pubsubmessageFields[0].Descriptor()
	// pubsubmessage.DefaultMessageID holds the default value on creation for the message_id field.
	pubsubmessage.DefaultMessageID = pubsubmessageDescMessageID.Default.(string)
	// pubsubmessageDescState is the schema descriptor for state field.
	pubsubmessageDescState := pubsubmessageFields[1].Descriptor()
	// pubsubmessage.DefaultState holds the default value on creation for the state field.
	pubsubmessage.DefaultState = pubsubmessageDescState.Default.(string)
	// pubsubmessageDescRespToID is the schema descriptor for resp_to_id field.
	pubsubmessageDescRespToID := pubsubmessageFields[2].Descriptor()
	// pubsubmessage.DefaultRespToID holds the default value on creation for the resp_to_id field.
	pubsubmessage.DefaultRespToID = pubsubmessageDescRespToID.Default.(func() uuid.UUID)
	// pubsubmessageDescUndoID is the schema descriptor for undo_id field.
	pubsubmessageDescUndoID := pubsubmessageFields[3].Descriptor()
	// pubsubmessage.DefaultUndoID holds the default value on creation for the undo_id field.
	pubsubmessage.DefaultUndoID = pubsubmessageDescUndoID.Default.(func() uuid.UUID)
	// pubsubmessageDescArguments is the schema descriptor for arguments field.
	pubsubmessageDescArguments := pubsubmessageFields[4].Descriptor()
	// pubsubmessage.DefaultArguments holds the default value on creation for the arguments field.
	pubsubmessage.DefaultArguments = pubsubmessageDescArguments.Default.(string)
}

const (
	Version = "v0.12.0" // Version of ent codegen.
)
