// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/NpoolPlatform/oplog-middleware/pkg/db/ent/oplog"
	"github.com/NpoolPlatform/oplog-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/oplog-middleware/pkg/db/ent/pubsubmessage"
	"github.com/google/uuid"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeOpLog         = "OpLog"
	TypePubsubMessage = "PubsubMessage"
)

// OpLogMutation represents an operation that mutates the OpLog nodes in the graph.
type OpLogMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	created_at           *uint32
	addcreated_at        *int32
	updated_at           *uint32
	addupdated_at        *int32
	deleted_at           *uint32
	adddeleted_at        *int32
	auto_id              *uint32
	addauto_id           *int32
	app_id               *uuid.UUID
	user_id              *uuid.UUID
	_path                *string
	method               *string
	arguments            *string
	cur_value            *string
	human_readable       *string
	result               *string
	fail_reason          *string
	elapsed_millisecs    *uint32
	addelapsed_millisecs *int32
	clearedFields        map[string]struct{}
	done                 bool
	oldValue             func(context.Context) (*OpLog, error)
	predicates           []predicate.OpLog
}

var _ ent.Mutation = (*OpLogMutation)(nil)

// oplogOption allows management of the mutation configuration using functional options.
type oplogOption func(*OpLogMutation)

// newOpLogMutation creates new mutation for the OpLog entity.
func newOpLogMutation(c config, op Op, opts ...oplogOption) *OpLogMutation {
	m := &OpLogMutation{
		config:        c,
		op:            op,
		typ:           TypeOpLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOpLogID sets the ID field of the mutation.
func withOpLogID(id uuid.UUID) oplogOption {
	return func(m *OpLogMutation) {
		var (
			err   error
			once  sync.Once
			value *OpLog
		)
		m.oldValue = func(ctx context.Context) (*OpLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().OpLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOpLog sets the old OpLog of the mutation.
func withOpLog(node *OpLog) oplogOption {
	return func(m *OpLogMutation) {
		m.oldValue = func(context.Context) (*OpLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OpLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OpLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of OpLog entities.
func (m *OpLogMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OpLogMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OpLogMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().OpLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *OpLogMutation) SetCreatedAt(u uint32) {
	m.created_at = &u
	m.addcreated_at = nil
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OpLogMutation) CreatedAt() (r uint32, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldCreatedAt(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// AddCreatedAt adds u to the "created_at" field.
func (m *OpLogMutation) AddCreatedAt(u int32) {
	if m.addcreated_at != nil {
		*m.addcreated_at += u
	} else {
		m.addcreated_at = &u
	}
}

// AddedCreatedAt returns the value that was added to the "created_at" field in this mutation.
func (m *OpLogMutation) AddedCreatedAt() (r int32, exists bool) {
	v := m.addcreated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OpLogMutation) ResetCreatedAt() {
	m.created_at = nil
	m.addcreated_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *OpLogMutation) SetUpdatedAt(u uint32) {
	m.updated_at = &u
	m.addupdated_at = nil
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *OpLogMutation) UpdatedAt() (r uint32, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldUpdatedAt(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// AddUpdatedAt adds u to the "updated_at" field.
func (m *OpLogMutation) AddUpdatedAt(u int32) {
	if m.addupdated_at != nil {
		*m.addupdated_at += u
	} else {
		m.addupdated_at = &u
	}
}

// AddedUpdatedAt returns the value that was added to the "updated_at" field in this mutation.
func (m *OpLogMutation) AddedUpdatedAt() (r int32, exists bool) {
	v := m.addupdated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *OpLogMutation) ResetUpdatedAt() {
	m.updated_at = nil
	m.addupdated_at = nil
}

// SetDeletedAt sets the "deleted_at" field.
func (m *OpLogMutation) SetDeletedAt(u uint32) {
	m.deleted_at = &u
	m.adddeleted_at = nil
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *OpLogMutation) DeletedAt() (r uint32, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldDeletedAt(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// AddDeletedAt adds u to the "deleted_at" field.
func (m *OpLogMutation) AddDeletedAt(u int32) {
	if m.adddeleted_at != nil {
		*m.adddeleted_at += u
	} else {
		m.adddeleted_at = &u
	}
}

// AddedDeletedAt returns the value that was added to the "deleted_at" field in this mutation.
func (m *OpLogMutation) AddedDeletedAt() (r int32, exists bool) {
	v := m.adddeleted_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *OpLogMutation) ResetDeletedAt() {
	m.deleted_at = nil
	m.adddeleted_at = nil
}

// SetAutoID sets the "auto_id" field.
func (m *OpLogMutation) SetAutoID(u uint32) {
	m.auto_id = &u
	m.addauto_id = nil
}

// AutoID returns the value of the "auto_id" field in the mutation.
func (m *OpLogMutation) AutoID() (r uint32, exists bool) {
	v := m.auto_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAutoID returns the old "auto_id" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldAutoID(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAutoID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAutoID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAutoID: %w", err)
	}
	return oldValue.AutoID, nil
}

// AddAutoID adds u to the "auto_id" field.
func (m *OpLogMutation) AddAutoID(u int32) {
	if m.addauto_id != nil {
		*m.addauto_id += u
	} else {
		m.addauto_id = &u
	}
}

// AddedAutoID returns the value that was added to the "auto_id" field in this mutation.
func (m *OpLogMutation) AddedAutoID() (r int32, exists bool) {
	v := m.addauto_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAutoID resets all changes to the "auto_id" field.
func (m *OpLogMutation) ResetAutoID() {
	m.auto_id = nil
	m.addauto_id = nil
}

// SetAppID sets the "app_id" field.
func (m *OpLogMutation) SetAppID(u uuid.UUID) {
	m.app_id = &u
}

// AppID returns the value of the "app_id" field in the mutation.
func (m *OpLogMutation) AppID() (r uuid.UUID, exists bool) {
	v := m.app_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAppID returns the old "app_id" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldAppID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppID: %w", err)
	}
	return oldValue.AppID, nil
}

// ClearAppID clears the value of the "app_id" field.
func (m *OpLogMutation) ClearAppID() {
	m.app_id = nil
	m.clearedFields[oplog.FieldAppID] = struct{}{}
}

// AppIDCleared returns if the "app_id" field was cleared in this mutation.
func (m *OpLogMutation) AppIDCleared() bool {
	_, ok := m.clearedFields[oplog.FieldAppID]
	return ok
}

// ResetAppID resets all changes to the "app_id" field.
func (m *OpLogMutation) ResetAppID() {
	m.app_id = nil
	delete(m.clearedFields, oplog.FieldAppID)
}

// SetUserID sets the "user_id" field.
func (m *OpLogMutation) SetUserID(u uuid.UUID) {
	m.user_id = &u
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *OpLogMutation) UserID() (r uuid.UUID, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldUserID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ClearUserID clears the value of the "user_id" field.
func (m *OpLogMutation) ClearUserID() {
	m.user_id = nil
	m.clearedFields[oplog.FieldUserID] = struct{}{}
}

// UserIDCleared returns if the "user_id" field was cleared in this mutation.
func (m *OpLogMutation) UserIDCleared() bool {
	_, ok := m.clearedFields[oplog.FieldUserID]
	return ok
}

// ResetUserID resets all changes to the "user_id" field.
func (m *OpLogMutation) ResetUserID() {
	m.user_id = nil
	delete(m.clearedFields, oplog.FieldUserID)
}

// SetPath sets the "path" field.
func (m *OpLogMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *OpLogMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ClearPath clears the value of the "path" field.
func (m *OpLogMutation) ClearPath() {
	m._path = nil
	m.clearedFields[oplog.FieldPath] = struct{}{}
}

// PathCleared returns if the "path" field was cleared in this mutation.
func (m *OpLogMutation) PathCleared() bool {
	_, ok := m.clearedFields[oplog.FieldPath]
	return ok
}

// ResetPath resets all changes to the "path" field.
func (m *OpLogMutation) ResetPath() {
	m._path = nil
	delete(m.clearedFields, oplog.FieldPath)
}

// SetMethod sets the "method" field.
func (m *OpLogMutation) SetMethod(s string) {
	m.method = &s
}

// Method returns the value of the "method" field in the mutation.
func (m *OpLogMutation) Method() (r string, exists bool) {
	v := m.method
	if v == nil {
		return
	}
	return *v, true
}

// OldMethod returns the old "method" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldMethod(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMethod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMethod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMethod: %w", err)
	}
	return oldValue.Method, nil
}

// ClearMethod clears the value of the "method" field.
func (m *OpLogMutation) ClearMethod() {
	m.method = nil
	m.clearedFields[oplog.FieldMethod] = struct{}{}
}

// MethodCleared returns if the "method" field was cleared in this mutation.
func (m *OpLogMutation) MethodCleared() bool {
	_, ok := m.clearedFields[oplog.FieldMethod]
	return ok
}

// ResetMethod resets all changes to the "method" field.
func (m *OpLogMutation) ResetMethod() {
	m.method = nil
	delete(m.clearedFields, oplog.FieldMethod)
}

// SetArguments sets the "arguments" field.
func (m *OpLogMutation) SetArguments(s string) {
	m.arguments = &s
}

// Arguments returns the value of the "arguments" field in the mutation.
func (m *OpLogMutation) Arguments() (r string, exists bool) {
	v := m.arguments
	if v == nil {
		return
	}
	return *v, true
}

// OldArguments returns the old "arguments" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldArguments(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldArguments is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldArguments requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldArguments: %w", err)
	}
	return oldValue.Arguments, nil
}

// ClearArguments clears the value of the "arguments" field.
func (m *OpLogMutation) ClearArguments() {
	m.arguments = nil
	m.clearedFields[oplog.FieldArguments] = struct{}{}
}

// ArgumentsCleared returns if the "arguments" field was cleared in this mutation.
func (m *OpLogMutation) ArgumentsCleared() bool {
	_, ok := m.clearedFields[oplog.FieldArguments]
	return ok
}

// ResetArguments resets all changes to the "arguments" field.
func (m *OpLogMutation) ResetArguments() {
	m.arguments = nil
	delete(m.clearedFields, oplog.FieldArguments)
}

// SetCurValue sets the "cur_value" field.
func (m *OpLogMutation) SetCurValue(s string) {
	m.cur_value = &s
}

// CurValue returns the value of the "cur_value" field in the mutation.
func (m *OpLogMutation) CurValue() (r string, exists bool) {
	v := m.cur_value
	if v == nil {
		return
	}
	return *v, true
}

// OldCurValue returns the old "cur_value" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldCurValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurValue: %w", err)
	}
	return oldValue.CurValue, nil
}

// ClearCurValue clears the value of the "cur_value" field.
func (m *OpLogMutation) ClearCurValue() {
	m.cur_value = nil
	m.clearedFields[oplog.FieldCurValue] = struct{}{}
}

// CurValueCleared returns if the "cur_value" field was cleared in this mutation.
func (m *OpLogMutation) CurValueCleared() bool {
	_, ok := m.clearedFields[oplog.FieldCurValue]
	return ok
}

// ResetCurValue resets all changes to the "cur_value" field.
func (m *OpLogMutation) ResetCurValue() {
	m.cur_value = nil
	delete(m.clearedFields, oplog.FieldCurValue)
}

// SetHumanReadable sets the "human_readable" field.
func (m *OpLogMutation) SetHumanReadable(s string) {
	m.human_readable = &s
}

// HumanReadable returns the value of the "human_readable" field in the mutation.
func (m *OpLogMutation) HumanReadable() (r string, exists bool) {
	v := m.human_readable
	if v == nil {
		return
	}
	return *v, true
}

// OldHumanReadable returns the old "human_readable" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldHumanReadable(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHumanReadable is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHumanReadable requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHumanReadable: %w", err)
	}
	return oldValue.HumanReadable, nil
}

// ClearHumanReadable clears the value of the "human_readable" field.
func (m *OpLogMutation) ClearHumanReadable() {
	m.human_readable = nil
	m.clearedFields[oplog.FieldHumanReadable] = struct{}{}
}

// HumanReadableCleared returns if the "human_readable" field was cleared in this mutation.
func (m *OpLogMutation) HumanReadableCleared() bool {
	_, ok := m.clearedFields[oplog.FieldHumanReadable]
	return ok
}

// ResetHumanReadable resets all changes to the "human_readable" field.
func (m *OpLogMutation) ResetHumanReadable() {
	m.human_readable = nil
	delete(m.clearedFields, oplog.FieldHumanReadable)
}

// SetResult sets the "result" field.
func (m *OpLogMutation) SetResult(s string) {
	m.result = &s
}

// Result returns the value of the "result" field in the mutation.
func (m *OpLogMutation) Result() (r string, exists bool) {
	v := m.result
	if v == nil {
		return
	}
	return *v, true
}

// OldResult returns the old "result" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldResult(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResult is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResult requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResult: %w", err)
	}
	return oldValue.Result, nil
}

// ClearResult clears the value of the "result" field.
func (m *OpLogMutation) ClearResult() {
	m.result = nil
	m.clearedFields[oplog.FieldResult] = struct{}{}
}

// ResultCleared returns if the "result" field was cleared in this mutation.
func (m *OpLogMutation) ResultCleared() bool {
	_, ok := m.clearedFields[oplog.FieldResult]
	return ok
}

// ResetResult resets all changes to the "result" field.
func (m *OpLogMutation) ResetResult() {
	m.result = nil
	delete(m.clearedFields, oplog.FieldResult)
}

// SetFailReason sets the "fail_reason" field.
func (m *OpLogMutation) SetFailReason(s string) {
	m.fail_reason = &s
}

// FailReason returns the value of the "fail_reason" field in the mutation.
func (m *OpLogMutation) FailReason() (r string, exists bool) {
	v := m.fail_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldFailReason returns the old "fail_reason" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldFailReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFailReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFailReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFailReason: %w", err)
	}
	return oldValue.FailReason, nil
}

// ClearFailReason clears the value of the "fail_reason" field.
func (m *OpLogMutation) ClearFailReason() {
	m.fail_reason = nil
	m.clearedFields[oplog.FieldFailReason] = struct{}{}
}

// FailReasonCleared returns if the "fail_reason" field was cleared in this mutation.
func (m *OpLogMutation) FailReasonCleared() bool {
	_, ok := m.clearedFields[oplog.FieldFailReason]
	return ok
}

// ResetFailReason resets all changes to the "fail_reason" field.
func (m *OpLogMutation) ResetFailReason() {
	m.fail_reason = nil
	delete(m.clearedFields, oplog.FieldFailReason)
}

// SetElapsedMillisecs sets the "elapsed_millisecs" field.
func (m *OpLogMutation) SetElapsedMillisecs(u uint32) {
	m.elapsed_millisecs = &u
	m.addelapsed_millisecs = nil
}

// ElapsedMillisecs returns the value of the "elapsed_millisecs" field in the mutation.
func (m *OpLogMutation) ElapsedMillisecs() (r uint32, exists bool) {
	v := m.elapsed_millisecs
	if v == nil {
		return
	}
	return *v, true
}

// OldElapsedMillisecs returns the old "elapsed_millisecs" field's value of the OpLog entity.
// If the OpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OpLogMutation) OldElapsedMillisecs(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldElapsedMillisecs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldElapsedMillisecs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldElapsedMillisecs: %w", err)
	}
	return oldValue.ElapsedMillisecs, nil
}

// AddElapsedMillisecs adds u to the "elapsed_millisecs" field.
func (m *OpLogMutation) AddElapsedMillisecs(u int32) {
	if m.addelapsed_millisecs != nil {
		*m.addelapsed_millisecs += u
	} else {
		m.addelapsed_millisecs = &u
	}
}

// AddedElapsedMillisecs returns the value that was added to the "elapsed_millisecs" field in this mutation.
func (m *OpLogMutation) AddedElapsedMillisecs() (r int32, exists bool) {
	v := m.addelapsed_millisecs
	if v == nil {
		return
	}
	return *v, true
}

// ClearElapsedMillisecs clears the value of the "elapsed_millisecs" field.
func (m *OpLogMutation) ClearElapsedMillisecs() {
	m.elapsed_millisecs = nil
	m.addelapsed_millisecs = nil
	m.clearedFields[oplog.FieldElapsedMillisecs] = struct{}{}
}

// ElapsedMillisecsCleared returns if the "elapsed_millisecs" field was cleared in this mutation.
func (m *OpLogMutation) ElapsedMillisecsCleared() bool {
	_, ok := m.clearedFields[oplog.FieldElapsedMillisecs]
	return ok
}

// ResetElapsedMillisecs resets all changes to the "elapsed_millisecs" field.
func (m *OpLogMutation) ResetElapsedMillisecs() {
	m.elapsed_millisecs = nil
	m.addelapsed_millisecs = nil
	delete(m.clearedFields, oplog.FieldElapsedMillisecs)
}

// Where appends a list predicates to the OpLogMutation builder.
func (m *OpLogMutation) Where(ps ...predicate.OpLog) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *OpLogMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (OpLog).
func (m *OpLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OpLogMutation) Fields() []string {
	fields := make([]string, 0, 14)
	if m.created_at != nil {
		fields = append(fields, oplog.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, oplog.FieldUpdatedAt)
	}
	if m.deleted_at != nil {
		fields = append(fields, oplog.FieldDeletedAt)
	}
	if m.auto_id != nil {
		fields = append(fields, oplog.FieldAutoID)
	}
	if m.app_id != nil {
		fields = append(fields, oplog.FieldAppID)
	}
	if m.user_id != nil {
		fields = append(fields, oplog.FieldUserID)
	}
	if m._path != nil {
		fields = append(fields, oplog.FieldPath)
	}
	if m.method != nil {
		fields = append(fields, oplog.FieldMethod)
	}
	if m.arguments != nil {
		fields = append(fields, oplog.FieldArguments)
	}
	if m.cur_value != nil {
		fields = append(fields, oplog.FieldCurValue)
	}
	if m.human_readable != nil {
		fields = append(fields, oplog.FieldHumanReadable)
	}
	if m.result != nil {
		fields = append(fields, oplog.FieldResult)
	}
	if m.fail_reason != nil {
		fields = append(fields, oplog.FieldFailReason)
	}
	if m.elapsed_millisecs != nil {
		fields = append(fields, oplog.FieldElapsedMillisecs)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OpLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case oplog.FieldCreatedAt:
		return m.CreatedAt()
	case oplog.FieldUpdatedAt:
		return m.UpdatedAt()
	case oplog.FieldDeletedAt:
		return m.DeletedAt()
	case oplog.FieldAutoID:
		return m.AutoID()
	case oplog.FieldAppID:
		return m.AppID()
	case oplog.FieldUserID:
		return m.UserID()
	case oplog.FieldPath:
		return m.Path()
	case oplog.FieldMethod:
		return m.Method()
	case oplog.FieldArguments:
		return m.Arguments()
	case oplog.FieldCurValue:
		return m.CurValue()
	case oplog.FieldHumanReadable:
		return m.HumanReadable()
	case oplog.FieldResult:
		return m.Result()
	case oplog.FieldFailReason:
		return m.FailReason()
	case oplog.FieldElapsedMillisecs:
		return m.ElapsedMillisecs()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OpLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case oplog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case oplog.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case oplog.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	case oplog.FieldAutoID:
		return m.OldAutoID(ctx)
	case oplog.FieldAppID:
		return m.OldAppID(ctx)
	case oplog.FieldUserID:
		return m.OldUserID(ctx)
	case oplog.FieldPath:
		return m.OldPath(ctx)
	case oplog.FieldMethod:
		return m.OldMethod(ctx)
	case oplog.FieldArguments:
		return m.OldArguments(ctx)
	case oplog.FieldCurValue:
		return m.OldCurValue(ctx)
	case oplog.FieldHumanReadable:
		return m.OldHumanReadable(ctx)
	case oplog.FieldResult:
		return m.OldResult(ctx)
	case oplog.FieldFailReason:
		return m.OldFailReason(ctx)
	case oplog.FieldElapsedMillisecs:
		return m.OldElapsedMillisecs(ctx)
	}
	return nil, fmt.Errorf("unknown OpLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OpLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case oplog.FieldCreatedAt:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case oplog.FieldUpdatedAt:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case oplog.FieldDeletedAt:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	case oplog.FieldAutoID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAutoID(v)
		return nil
	case oplog.FieldAppID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppID(v)
		return nil
	case oplog.FieldUserID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case oplog.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case oplog.FieldMethod:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMethod(v)
		return nil
	case oplog.FieldArguments:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetArguments(v)
		return nil
	case oplog.FieldCurValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurValue(v)
		return nil
	case oplog.FieldHumanReadable:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHumanReadable(v)
		return nil
	case oplog.FieldResult:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResult(v)
		return nil
	case oplog.FieldFailReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFailReason(v)
		return nil
	case oplog.FieldElapsedMillisecs:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetElapsedMillisecs(v)
		return nil
	}
	return fmt.Errorf("unknown OpLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OpLogMutation) AddedFields() []string {
	var fields []string
	if m.addcreated_at != nil {
		fields = append(fields, oplog.FieldCreatedAt)
	}
	if m.addupdated_at != nil {
		fields = append(fields, oplog.FieldUpdatedAt)
	}
	if m.adddeleted_at != nil {
		fields = append(fields, oplog.FieldDeletedAt)
	}
	if m.addauto_id != nil {
		fields = append(fields, oplog.FieldAutoID)
	}
	if m.addelapsed_millisecs != nil {
		fields = append(fields, oplog.FieldElapsedMillisecs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OpLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case oplog.FieldCreatedAt:
		return m.AddedCreatedAt()
	case oplog.FieldUpdatedAt:
		return m.AddedUpdatedAt()
	case oplog.FieldDeletedAt:
		return m.AddedDeletedAt()
	case oplog.FieldAutoID:
		return m.AddedAutoID()
	case oplog.FieldElapsedMillisecs:
		return m.AddedElapsedMillisecs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OpLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case oplog.FieldCreatedAt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedAt(v)
		return nil
	case oplog.FieldUpdatedAt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdatedAt(v)
		return nil
	case oplog.FieldDeletedAt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeletedAt(v)
		return nil
	case oplog.FieldAutoID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAutoID(v)
		return nil
	case oplog.FieldElapsedMillisecs:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddElapsedMillisecs(v)
		return nil
	}
	return fmt.Errorf("unknown OpLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OpLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(oplog.FieldAppID) {
		fields = append(fields, oplog.FieldAppID)
	}
	if m.FieldCleared(oplog.FieldUserID) {
		fields = append(fields, oplog.FieldUserID)
	}
	if m.FieldCleared(oplog.FieldPath) {
		fields = append(fields, oplog.FieldPath)
	}
	if m.FieldCleared(oplog.FieldMethod) {
		fields = append(fields, oplog.FieldMethod)
	}
	if m.FieldCleared(oplog.FieldArguments) {
		fields = append(fields, oplog.FieldArguments)
	}
	if m.FieldCleared(oplog.FieldCurValue) {
		fields = append(fields, oplog.FieldCurValue)
	}
	if m.FieldCleared(oplog.FieldHumanReadable) {
		fields = append(fields, oplog.FieldHumanReadable)
	}
	if m.FieldCleared(oplog.FieldResult) {
		fields = append(fields, oplog.FieldResult)
	}
	if m.FieldCleared(oplog.FieldFailReason) {
		fields = append(fields, oplog.FieldFailReason)
	}
	if m.FieldCleared(oplog.FieldElapsedMillisecs) {
		fields = append(fields, oplog.FieldElapsedMillisecs)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OpLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OpLogMutation) ClearField(name string) error {
	switch name {
	case oplog.FieldAppID:
		m.ClearAppID()
		return nil
	case oplog.FieldUserID:
		m.ClearUserID()
		return nil
	case oplog.FieldPath:
		m.ClearPath()
		return nil
	case oplog.FieldMethod:
		m.ClearMethod()
		return nil
	case oplog.FieldArguments:
		m.ClearArguments()
		return nil
	case oplog.FieldCurValue:
		m.ClearCurValue()
		return nil
	case oplog.FieldHumanReadable:
		m.ClearHumanReadable()
		return nil
	case oplog.FieldResult:
		m.ClearResult()
		return nil
	case oplog.FieldFailReason:
		m.ClearFailReason()
		return nil
	case oplog.FieldElapsedMillisecs:
		m.ClearElapsedMillisecs()
		return nil
	}
	return fmt.Errorf("unknown OpLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OpLogMutation) ResetField(name string) error {
	switch name {
	case oplog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case oplog.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case oplog.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	case oplog.FieldAutoID:
		m.ResetAutoID()
		return nil
	case oplog.FieldAppID:
		m.ResetAppID()
		return nil
	case oplog.FieldUserID:
		m.ResetUserID()
		return nil
	case oplog.FieldPath:
		m.ResetPath()
		return nil
	case oplog.FieldMethod:
		m.ResetMethod()
		return nil
	case oplog.FieldArguments:
		m.ResetArguments()
		return nil
	case oplog.FieldCurValue:
		m.ResetCurValue()
		return nil
	case oplog.FieldHumanReadable:
		m.ResetHumanReadable()
		return nil
	case oplog.FieldResult:
		m.ResetResult()
		return nil
	case oplog.FieldFailReason:
		m.ResetFailReason()
		return nil
	case oplog.FieldElapsedMillisecs:
		m.ResetElapsedMillisecs()
		return nil
	}
	return fmt.Errorf("unknown OpLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OpLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OpLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OpLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OpLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OpLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OpLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OpLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OpLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OpLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OpLog edge %s", name)
}

// PubsubMessageMutation represents an operation that mutates the PubsubMessage nodes in the graph.
type PubsubMessageMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	created_at    *uint32
	addcreated_at *int32
	updated_at    *uint32
	addupdated_at *int32
	deleted_at    *uint32
	adddeleted_at *int32
	auto_id       *uint32
	addauto_id    *int32
	message_id    *string
	state         *string
	resp_to_id    *uuid.UUID
	undo_id       *uuid.UUID
	arguments     *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PubsubMessage, error)
	predicates    []predicate.PubsubMessage
}

var _ ent.Mutation = (*PubsubMessageMutation)(nil)

// pubsubmessageOption allows management of the mutation configuration using functional options.
type pubsubmessageOption func(*PubsubMessageMutation)

// newPubsubMessageMutation creates new mutation for the PubsubMessage entity.
func newPubsubMessageMutation(c config, op Op, opts ...pubsubmessageOption) *PubsubMessageMutation {
	m := &PubsubMessageMutation{
		config:        c,
		op:            op,
		typ:           TypePubsubMessage,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPubsubMessageID sets the ID field of the mutation.
func withPubsubMessageID(id uuid.UUID) pubsubmessageOption {
	return func(m *PubsubMessageMutation) {
		var (
			err   error
			once  sync.Once
			value *PubsubMessage
		)
		m.oldValue = func(ctx context.Context) (*PubsubMessage, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PubsubMessage.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPubsubMessage sets the old PubsubMessage of the mutation.
func withPubsubMessage(node *PubsubMessage) pubsubmessageOption {
	return func(m *PubsubMessageMutation) {
		m.oldValue = func(context.Context) (*PubsubMessage, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PubsubMessageMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PubsubMessageMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PubsubMessage entities.
func (m *PubsubMessageMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PubsubMessageMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PubsubMessageMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PubsubMessage.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *PubsubMessageMutation) SetCreatedAt(u uint32) {
	m.created_at = &u
	m.addcreated_at = nil
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PubsubMessageMutation) CreatedAt() (r uint32, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldCreatedAt(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// AddCreatedAt adds u to the "created_at" field.
func (m *PubsubMessageMutation) AddCreatedAt(u int32) {
	if m.addcreated_at != nil {
		*m.addcreated_at += u
	} else {
		m.addcreated_at = &u
	}
}

// AddedCreatedAt returns the value that was added to the "created_at" field in this mutation.
func (m *PubsubMessageMutation) AddedCreatedAt() (r int32, exists bool) {
	v := m.addcreated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PubsubMessageMutation) ResetCreatedAt() {
	m.created_at = nil
	m.addcreated_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PubsubMessageMutation) SetUpdatedAt(u uint32) {
	m.updated_at = &u
	m.addupdated_at = nil
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PubsubMessageMutation) UpdatedAt() (r uint32, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldUpdatedAt(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// AddUpdatedAt adds u to the "updated_at" field.
func (m *PubsubMessageMutation) AddUpdatedAt(u int32) {
	if m.addupdated_at != nil {
		*m.addupdated_at += u
	} else {
		m.addupdated_at = &u
	}
}

// AddedUpdatedAt returns the value that was added to the "updated_at" field in this mutation.
func (m *PubsubMessageMutation) AddedUpdatedAt() (r int32, exists bool) {
	v := m.addupdated_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PubsubMessageMutation) ResetUpdatedAt() {
	m.updated_at = nil
	m.addupdated_at = nil
}

// SetDeletedAt sets the "deleted_at" field.
func (m *PubsubMessageMutation) SetDeletedAt(u uint32) {
	m.deleted_at = &u
	m.adddeleted_at = nil
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *PubsubMessageMutation) DeletedAt() (r uint32, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldDeletedAt(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// AddDeletedAt adds u to the "deleted_at" field.
func (m *PubsubMessageMutation) AddDeletedAt(u int32) {
	if m.adddeleted_at != nil {
		*m.adddeleted_at += u
	} else {
		m.adddeleted_at = &u
	}
}

// AddedDeletedAt returns the value that was added to the "deleted_at" field in this mutation.
func (m *PubsubMessageMutation) AddedDeletedAt() (r int32, exists bool) {
	v := m.adddeleted_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *PubsubMessageMutation) ResetDeletedAt() {
	m.deleted_at = nil
	m.adddeleted_at = nil
}

// SetAutoID sets the "auto_id" field.
func (m *PubsubMessageMutation) SetAutoID(u uint32) {
	m.auto_id = &u
	m.addauto_id = nil
}

// AutoID returns the value of the "auto_id" field in the mutation.
func (m *PubsubMessageMutation) AutoID() (r uint32, exists bool) {
	v := m.auto_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAutoID returns the old "auto_id" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldAutoID(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAutoID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAutoID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAutoID: %w", err)
	}
	return oldValue.AutoID, nil
}

// AddAutoID adds u to the "auto_id" field.
func (m *PubsubMessageMutation) AddAutoID(u int32) {
	if m.addauto_id != nil {
		*m.addauto_id += u
	} else {
		m.addauto_id = &u
	}
}

// AddedAutoID returns the value that was added to the "auto_id" field in this mutation.
func (m *PubsubMessageMutation) AddedAutoID() (r int32, exists bool) {
	v := m.addauto_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAutoID resets all changes to the "auto_id" field.
func (m *PubsubMessageMutation) ResetAutoID() {
	m.auto_id = nil
	m.addauto_id = nil
}

// SetMessageID sets the "message_id" field.
func (m *PubsubMessageMutation) SetMessageID(s string) {
	m.message_id = &s
}

// MessageID returns the value of the "message_id" field in the mutation.
func (m *PubsubMessageMutation) MessageID() (r string, exists bool) {
	v := m.message_id
	if v == nil {
		return
	}
	return *v, true
}

// OldMessageID returns the old "message_id" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldMessageID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMessageID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMessageID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMessageID: %w", err)
	}
	return oldValue.MessageID, nil
}

// ClearMessageID clears the value of the "message_id" field.
func (m *PubsubMessageMutation) ClearMessageID() {
	m.message_id = nil
	m.clearedFields[pubsubmessage.FieldMessageID] = struct{}{}
}

// MessageIDCleared returns if the "message_id" field was cleared in this mutation.
func (m *PubsubMessageMutation) MessageIDCleared() bool {
	_, ok := m.clearedFields[pubsubmessage.FieldMessageID]
	return ok
}

// ResetMessageID resets all changes to the "message_id" field.
func (m *PubsubMessageMutation) ResetMessageID() {
	m.message_id = nil
	delete(m.clearedFields, pubsubmessage.FieldMessageID)
}

// SetState sets the "state" field.
func (m *PubsubMessageMutation) SetState(s string) {
	m.state = &s
}

// State returns the value of the "state" field in the mutation.
func (m *PubsubMessageMutation) State() (r string, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldState(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ClearState clears the value of the "state" field.
func (m *PubsubMessageMutation) ClearState() {
	m.state = nil
	m.clearedFields[pubsubmessage.FieldState] = struct{}{}
}

// StateCleared returns if the "state" field was cleared in this mutation.
func (m *PubsubMessageMutation) StateCleared() bool {
	_, ok := m.clearedFields[pubsubmessage.FieldState]
	return ok
}

// ResetState resets all changes to the "state" field.
func (m *PubsubMessageMutation) ResetState() {
	m.state = nil
	delete(m.clearedFields, pubsubmessage.FieldState)
}

// SetRespToID sets the "resp_to_id" field.
func (m *PubsubMessageMutation) SetRespToID(u uuid.UUID) {
	m.resp_to_id = &u
}

// RespToID returns the value of the "resp_to_id" field in the mutation.
func (m *PubsubMessageMutation) RespToID() (r uuid.UUID, exists bool) {
	v := m.resp_to_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRespToID returns the old "resp_to_id" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldRespToID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRespToID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRespToID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRespToID: %w", err)
	}
	return oldValue.RespToID, nil
}

// ClearRespToID clears the value of the "resp_to_id" field.
func (m *PubsubMessageMutation) ClearRespToID() {
	m.resp_to_id = nil
	m.clearedFields[pubsubmessage.FieldRespToID] = struct{}{}
}

// RespToIDCleared returns if the "resp_to_id" field was cleared in this mutation.
func (m *PubsubMessageMutation) RespToIDCleared() bool {
	_, ok := m.clearedFields[pubsubmessage.FieldRespToID]
	return ok
}

// ResetRespToID resets all changes to the "resp_to_id" field.
func (m *PubsubMessageMutation) ResetRespToID() {
	m.resp_to_id = nil
	delete(m.clearedFields, pubsubmessage.FieldRespToID)
}

// SetUndoID sets the "undo_id" field.
func (m *PubsubMessageMutation) SetUndoID(u uuid.UUID) {
	m.undo_id = &u
}

// UndoID returns the value of the "undo_id" field in the mutation.
func (m *PubsubMessageMutation) UndoID() (r uuid.UUID, exists bool) {
	v := m.undo_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUndoID returns the old "undo_id" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldUndoID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUndoID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUndoID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUndoID: %w", err)
	}
	return oldValue.UndoID, nil
}

// ClearUndoID clears the value of the "undo_id" field.
func (m *PubsubMessageMutation) ClearUndoID() {
	m.undo_id = nil
	m.clearedFields[pubsubmessage.FieldUndoID] = struct{}{}
}

// UndoIDCleared returns if the "undo_id" field was cleared in this mutation.
func (m *PubsubMessageMutation) UndoIDCleared() bool {
	_, ok := m.clearedFields[pubsubmessage.FieldUndoID]
	return ok
}

// ResetUndoID resets all changes to the "undo_id" field.
func (m *PubsubMessageMutation) ResetUndoID() {
	m.undo_id = nil
	delete(m.clearedFields, pubsubmessage.FieldUndoID)
}

// SetArguments sets the "arguments" field.
func (m *PubsubMessageMutation) SetArguments(s string) {
	m.arguments = &s
}

// Arguments returns the value of the "arguments" field in the mutation.
func (m *PubsubMessageMutation) Arguments() (r string, exists bool) {
	v := m.arguments
	if v == nil {
		return
	}
	return *v, true
}

// OldArguments returns the old "arguments" field's value of the PubsubMessage entity.
// If the PubsubMessage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PubsubMessageMutation) OldArguments(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldArguments is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldArguments requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldArguments: %w", err)
	}
	return oldValue.Arguments, nil
}

// ClearArguments clears the value of the "arguments" field.
func (m *PubsubMessageMutation) ClearArguments() {
	m.arguments = nil
	m.clearedFields[pubsubmessage.FieldArguments] = struct{}{}
}

// ArgumentsCleared returns if the "arguments" field was cleared in this mutation.
func (m *PubsubMessageMutation) ArgumentsCleared() bool {
	_, ok := m.clearedFields[pubsubmessage.FieldArguments]
	return ok
}

// ResetArguments resets all changes to the "arguments" field.
func (m *PubsubMessageMutation) ResetArguments() {
	m.arguments = nil
	delete(m.clearedFields, pubsubmessage.FieldArguments)
}

// Where appends a list predicates to the PubsubMessageMutation builder.
func (m *PubsubMessageMutation) Where(ps ...predicate.PubsubMessage) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *PubsubMessageMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (PubsubMessage).
func (m *PubsubMessageMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PubsubMessageMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.created_at != nil {
		fields = append(fields, pubsubmessage.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, pubsubmessage.FieldUpdatedAt)
	}
	if m.deleted_at != nil {
		fields = append(fields, pubsubmessage.FieldDeletedAt)
	}
	if m.auto_id != nil {
		fields = append(fields, pubsubmessage.FieldAutoID)
	}
	if m.message_id != nil {
		fields = append(fields, pubsubmessage.FieldMessageID)
	}
	if m.state != nil {
		fields = append(fields, pubsubmessage.FieldState)
	}
	if m.resp_to_id != nil {
		fields = append(fields, pubsubmessage.FieldRespToID)
	}
	if m.undo_id != nil {
		fields = append(fields, pubsubmessage.FieldUndoID)
	}
	if m.arguments != nil {
		fields = append(fields, pubsubmessage.FieldArguments)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PubsubMessageMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pubsubmessage.FieldCreatedAt:
		return m.CreatedAt()
	case pubsubmessage.FieldUpdatedAt:
		return m.UpdatedAt()
	case pubsubmessage.FieldDeletedAt:
		return m.DeletedAt()
	case pubsubmessage.FieldAutoID:
		return m.AutoID()
	case pubsubmessage.FieldMessageID:
		return m.MessageID()
	case pubsubmessage.FieldState:
		return m.State()
	case pubsubmessage.FieldRespToID:
		return m.RespToID()
	case pubsubmessage.FieldUndoID:
		return m.UndoID()
	case pubsubmessage.FieldArguments:
		return m.Arguments()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PubsubMessageMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pubsubmessage.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case pubsubmessage.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case pubsubmessage.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	case pubsubmessage.FieldAutoID:
		return m.OldAutoID(ctx)
	case pubsubmessage.FieldMessageID:
		return m.OldMessageID(ctx)
	case pubsubmessage.FieldState:
		return m.OldState(ctx)
	case pubsubmessage.FieldRespToID:
		return m.OldRespToID(ctx)
	case pubsubmessage.FieldUndoID:
		return m.OldUndoID(ctx)
	case pubsubmessage.FieldArguments:
		return m.OldArguments(ctx)
	}
	return nil, fmt.Errorf("unknown PubsubMessage field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PubsubMessageMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pubsubmessage.FieldCreatedAt:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case pubsubmessage.FieldUpdatedAt:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case pubsubmessage.FieldDeletedAt:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	case pubsubmessage.FieldAutoID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAutoID(v)
		return nil
	case pubsubmessage.FieldMessageID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMessageID(v)
		return nil
	case pubsubmessage.FieldState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case pubsubmessage.FieldRespToID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRespToID(v)
		return nil
	case pubsubmessage.FieldUndoID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUndoID(v)
		return nil
	case pubsubmessage.FieldArguments:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetArguments(v)
		return nil
	}
	return fmt.Errorf("unknown PubsubMessage field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PubsubMessageMutation) AddedFields() []string {
	var fields []string
	if m.addcreated_at != nil {
		fields = append(fields, pubsubmessage.FieldCreatedAt)
	}
	if m.addupdated_at != nil {
		fields = append(fields, pubsubmessage.FieldUpdatedAt)
	}
	if m.adddeleted_at != nil {
		fields = append(fields, pubsubmessage.FieldDeletedAt)
	}
	if m.addauto_id != nil {
		fields = append(fields, pubsubmessage.FieldAutoID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PubsubMessageMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pubsubmessage.FieldCreatedAt:
		return m.AddedCreatedAt()
	case pubsubmessage.FieldUpdatedAt:
		return m.AddedUpdatedAt()
	case pubsubmessage.FieldDeletedAt:
		return m.AddedDeletedAt()
	case pubsubmessage.FieldAutoID:
		return m.AddedAutoID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PubsubMessageMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pubsubmessage.FieldCreatedAt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedAt(v)
		return nil
	case pubsubmessage.FieldUpdatedAt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdatedAt(v)
		return nil
	case pubsubmessage.FieldDeletedAt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeletedAt(v)
		return nil
	case pubsubmessage.FieldAutoID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAutoID(v)
		return nil
	}
	return fmt.Errorf("unknown PubsubMessage numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PubsubMessageMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(pubsubmessage.FieldMessageID) {
		fields = append(fields, pubsubmessage.FieldMessageID)
	}
	if m.FieldCleared(pubsubmessage.FieldState) {
		fields = append(fields, pubsubmessage.FieldState)
	}
	if m.FieldCleared(pubsubmessage.FieldRespToID) {
		fields = append(fields, pubsubmessage.FieldRespToID)
	}
	if m.FieldCleared(pubsubmessage.FieldUndoID) {
		fields = append(fields, pubsubmessage.FieldUndoID)
	}
	if m.FieldCleared(pubsubmessage.FieldArguments) {
		fields = append(fields, pubsubmessage.FieldArguments)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PubsubMessageMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PubsubMessageMutation) ClearField(name string) error {
	switch name {
	case pubsubmessage.FieldMessageID:
		m.ClearMessageID()
		return nil
	case pubsubmessage.FieldState:
		m.ClearState()
		return nil
	case pubsubmessage.FieldRespToID:
		m.ClearRespToID()
		return nil
	case pubsubmessage.FieldUndoID:
		m.ClearUndoID()
		return nil
	case pubsubmessage.FieldArguments:
		m.ClearArguments()
		return nil
	}
	return fmt.Errorf("unknown PubsubMessage nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PubsubMessageMutation) ResetField(name string) error {
	switch name {
	case pubsubmessage.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case pubsubmessage.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case pubsubmessage.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	case pubsubmessage.FieldAutoID:
		m.ResetAutoID()
		return nil
	case pubsubmessage.FieldMessageID:
		m.ResetMessageID()
		return nil
	case pubsubmessage.FieldState:
		m.ResetState()
		return nil
	case pubsubmessage.FieldRespToID:
		m.ResetRespToID()
		return nil
	case pubsubmessage.FieldUndoID:
		m.ResetUndoID()
		return nil
	case pubsubmessage.FieldArguments:
		m.ResetArguments()
		return nil
	}
	return fmt.Errorf("unknown PubsubMessage field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PubsubMessageMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PubsubMessageMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PubsubMessageMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PubsubMessageMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PubsubMessageMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PubsubMessageMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PubsubMessageMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PubsubMessage unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PubsubMessageMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PubsubMessage edge %s", name)
}
