// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OpLog is the predicate function for oplog builders.
type OpLog func(*sql.Selector)

// PubsubMessage is the predicate function for pubsubmessage builders.
type PubsubMessage func(*sql.Selector)
